name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-release:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: waifu
            asset_name: waifu-x86_64-linux-gnu
          # Linux aarch64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: waifu
            asset_name: waifu-aarch64-linux-gnu
          # macOS x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: waifu
            asset_name: waifu-x86_64-darwin
          # macOS aarch64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: waifu
            asset_name: waifu-aarch64-darwin
          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: waifu.exe
            asset_name: waifu-x86_64-windows.exe
          # Windows aarch64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact_name: waifu.exe
            asset_name: waifu-aarch64-windows.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation tools
      if: runner.os == 'Linux'
      run: |
        sudo dpkg --add-architecture arm64
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu
        sudo apt-get install -y libssl-dev pkg-config
        sudo apt-get install -y libssl-dev:arm64
        sudo apt-get install -y gcc-multilib
        echo 'PKG_CONFIG_ALLOW_CROSS=1' >> $GITHUB_ENV
        echo 'OPENSSL_DIR=/usr/include/aarch64-linux-gnu' >> $GITHUB_ENV
        echo 'OPENSSL_LIB_DIR=/usr/lib/aarch64-linux-gnu' >> $GITHUB_ENV

    - name: Build
      shell: bash
      env:
        PKG_CONFIG_ALLOW_CROSS: "1"
      run: |
        if [ "${{ matrix.target }}" = "aarch64-unknown-linux-gnu" ]; then
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc \
          PKG_CONFIG_SYSROOT_DIR=/usr/lib/aarch64-linux-gnu \
          PKG_CONFIG_PATH=/usr/lib/aarch64-linux-gnu/pkgconfig \
          cargo build --release --target ${{ matrix.target }}
        else
          cargo build --release --target ${{ matrix.target }}
        fi

    - name: Install UPX
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Linux" ]; then
          sudo apt-get install -y upx
        elif [ "${{ runner.os }}" == "Windows" ]; then
          choco install upx
        fi

    - name: Compress Binary with UPX
      shell: bash
      run: |
        if [[ "${{ matrix.target }}" != *"aarch64"* ]] && [[ "${{ runner.os }}" != "macOS" ]]; then
          upx --ultra-brute target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        fi

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/octet-stream