name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  build-release:
    needs: create-release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # Linux x86_64
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: waifu
            asset_name: waifu-x86_64-linux-gnu
          # Linux aarch64
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
            artifact_name: waifu
            asset_name: waifu-aarch64-linux-gnu
          # Linux x86_64 MUSL
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
            artifact_name: waifu
            asset_name: waifu-x86_64-linux-musl
          # Linux aarch64 MUSL
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
            artifact_name: waifu
            asset_name: waifu-aarch64-linux-musl
          # macOS x86_64
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: waifu
            asset_name: waifu-x86_64-darwin
          # macOS aarch64
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: waifu
            asset_name: waifu-aarch64-darwin
          # Windows x86_64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: waifu.exe
            asset_name: waifu-x86_64-windows.exe
          # Windows aarch64
          - os: windows-latest
            target: aarch64-pc-windows-msvc
            artifact_name: waifu.exe
            asset_name: waifu-aarch64-windows.exe

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        targets: ${{ matrix.target }}

    - name: Install cross-compilation tools
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu

    - name: Build
      run: |
        cargo build --release --target ${{ matrix.target }}

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create-release.outputs.upload_url }}
        asset_path: target/${{ matrix.target }}/release/${{ matrix.artifact_name }}
        asset_name: ${{ matrix.asset_name }}
        asset_content_type: application/octet-stream